import React from 'react';
import { TournamentRuleItem, SupplementaryRegulation } from '../types/tournament';
import { DEFAULT_SUPPLEMENTARY_REGULATIONS } from '../data/tournamentData';
import { FileText, CheckCircle2, ChevronRight } from 'lucide-react';

interface RulesSectionProps {
  rules: TournamentRuleItem[];
  supplementaryRegulations?: SupplementaryRegulation[];
}

/**
 * Render text with support for bold formatting (**text**), italic (*text*), and check circle icon ([v] / (v))
 */
const renderFormattedInline = (text: string) => {
  if (!text) return null;

  // Split by bold (**...**), italic (*...*), checkmarks ([v] or (v)), and special badges
  // Tokens: (**...**), (*...*), (\[v\]|\(v\)|\[check\])
  const regex = /(\*\*.*?\*\*|\*.*?\*|\[v\]|\(v\)|\[check\])/g;
  const parts = text.split(regex);

  return parts.map((part, pIdx) => {
    if (!part) return null;

    if (part.startsWith('**') && part.endsWith('**') && part.length >= 4) {
      return (
        <strong key={pIdx} className="font-bold text-slate-900">
          {part.slice(2, -2)}
        </strong>
      );
    }

    if (part.startsWith('*') && part.endsWith('*') && part.length >= 2 && !part.startsWith('**')) {
      return (
        <em key={pIdx} className="italic text-slate-800">
          {part.slice(1, -1)}
        </em>
      );
    }

    if (part === '[v]' || part === '(v)' || part === '[check]') {
      return (
        <CheckCircle2
          key={pIdx}
          className="w-4 h-4 text-blue-600 inline-block shrink-0 align-text-bottom mr-1"
        />
      );
    }

    return <span key={pIdx}>{part}</span>;
  });
};

/**
 * Render multi-line formatted text preserving newlines, indentation, paragraph spacing, and bolding.
 * Supports both modern WYSIWYG HTML output and legacy markdown/token formats.
 */
export const FormattedText: React.FC<{ text: string; className?: string }> = ({ text, className = '' }) => {
  if (!text) return null;

  // Check if string contains HTML tags generated by WYSIWYG rich text editor
  const isHtml = /<[a-z][\s\S]*>/i.test(text);

  if (isHtml) {
    return (
      <div
        className={`prose-sm max-w-none text-slate-700 font-normal leading-relaxed text-justify space-y-1.5 [&_strong]:text-slate-900 [&_strong]:font-bold [&_em]:text-slate-800 [&_ul]:list-disc [&_ul]:pl-5 [&_ol]:list-decimal [&_ol]:pl-5 [&_p]:my-1 [&_p]:leading-relaxed [&_p]:font-normal ${className}`}
        dangerouslySetInnerHTML={{ __html: text }}
      />
    );
  }

  const lines = text.split('\n');

  return (
    <div className={`space-y-1.5 font-normal text-slate-700 ${className}`}>
      {lines.map((line, lIdx) => {
        // Calculate indentation level from leading spaces or tabs
        const leadingSpacesMatch = line.match(/^(\s+)/);
        const indentLevel = leadingSpacesMatch ? Math.min(Math.floor(leadingSpacesMatch[1].length / 2), 4) : 0;
        const indentClass = indentLevel === 1 ? 'pl-3' : indentLevel === 2 ? 'pl-6' : indentLevel >= 3 ? 'pl-9' : '';

        const trimmed = line.trim();
        if (!trimmed) {
          return <div key={lIdx} className="h-1.5" />;
        }

        // Check circle item prefix: [v] or (v)
        if (trimmed.startsWith('[v] ') || trimmed.startsWith('(v) ') || trimmed.startsWith('[check] ')) {
          const content = trimmed.replace(/^(\[v\]|\(v\)|\[check\])\s+/, '');
          return (
            <div key={lIdx} className={`flex items-start gap-2 ${indentClass}`}>
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div className="leading-relaxed text-justify w-full font-normal">
                {renderFormattedInline(content)}
              </div>
            </div>
          );
        }

        // Bullet point line
        if (trimmed.startsWith('- ') || trimmed.startsWith('• ') || trimmed.startsWith('* ')) {
          const content = trimmed.substring(2);
          return (
            <div key={lIdx} className={`flex items-start gap-2 pl-1 ${indentClass}`}>
              <span className="text-blue-600 font-bold shrink-0 mt-0.5">•</span>
              <div className="leading-relaxed text-justify w-full font-normal">
                {renderFormattedInline(content)}
              </div>
            </div>
          );
        }

        // Numbered list items e.g. "1) ", "2) ", "1. "
        const numberMatch = trimmed.match(/^(\d+[\.\)])\s+(.*)/);
        if (numberMatch) {
          const num = numberMatch[1];
          const content = numberMatch[2];
          return (
            <div key={lIdx} className={`flex items-start gap-1.5 ${indentClass}`}>
              <span className="font-bold text-slate-900 shrink-0 mt-0.5 text-xs sm:text-sm">{num}</span>
              <div className="leading-relaxed text-justify w-full font-normal">
                {renderFormattedInline(content)}
              </div>
            </div>
          );
        }

        // Emoji list items: ✅, ❌, ⚠️, 📌, 👉, ⭐
        const emojiMatch = trimmed.match(/^([✅❌⚠️📌👉⭐])\s+(.*)/);
        if (emojiMatch) {
          const emoji = emojiMatch[1];
          const content = emojiMatch[2];
          return (
            <div key={lIdx} className={`flex items-start gap-2 ${indentClass}`}>
              <span className="shrink-0 mt-0.5 text-xs sm:text-sm">{emoji}</span>
              <div className="leading-relaxed text-justify w-full font-normal">
                {renderFormattedInline(content)}
              </div>
            </div>
          );
        }

        return (
          <p key={lIdx} className={`leading-relaxed text-justify font-normal ${indentClass}`}>
            {renderFormattedInline(trimmed)}
          </p>
        );
      })}
    </div>
  );
};

/**
 * Helper to render scoring rule items with beautiful structured formatting
 * especially when a rule item contains multi-priority ranking rules (1., 2., 3., 4.).
 */
const renderRuleItem = (sc: string, sIdx: number) => {
  // Check if this item is a combined ranking rule with 1., 2., 3., 4.
  const hasRankingPriorities =
    sc.includes('Quy tắc xếp hạng') ||
    sc.includes('1. Ưu tiên') ||
    sc.includes('1. Xét') ||
    sc.includes('2. Nếu') ||
    sc.includes('2. Xét');

  if (hasRankingPriorities && (sc.includes('1.') && sc.includes('2.'))) {
    const prefix = sc.includes(':') ? sc.split(':')[0] + ':' : 'Quy tắc xếp hạng:';
    
    return (
      <li key={sIdx} className="flex items-start gap-2 pt-0.5">
        <CheckCircle2 className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
        <div className="w-full space-y-1.5 text-xs sm:text-sm text-slate-700 leading-relaxed text-justify">
          <span className="font-bold text-slate-900 block text-left">
            {prefix}
          </span>
          <div className="space-y-1.5 pl-0.5">
            <p className="text-justify">
              <strong className="text-slate-900">1) Ưu tiên số trận thắng</strong> (1 trận thắng = 1 điểm).
            </p>
            <p className="text-justify">
              <strong className="text-slate-900">2) Nếu đồng số trận thắng:</strong> Xét hệ số điểm bị thua trên trận thua (đội bị thua ít điểm hơn xếp trên. Ví dụ: Thua 19–21 [thua 2 điểm] xếp trên Thua 17–21 [thua 4 điểm]).
            </p>
            <p className="text-justify">
              <strong className="text-slate-900">3) Xét hiệu số điểm thắng / thua</strong> toàn giải.
            </p>
            <p className="text-justify">
              <strong className="text-slate-900">4) Tổng điểm thắng</strong> toàn giải.
            </p>
          </div>
        </div>
      </li>
    );
  }

  // Normal rule item (supports HTML, newlines, bold, italic, indentation, custom icons)
  const trimmed = sc.trim();
  const startsWithCustomIcon = trimmed.startsWith('[v]') || trimmed.startsWith('(v)') || trimmed.startsWith('[check]');
  const isHtml = /<[a-z][\s\S]*>/i.test(sc);

  return (
    <li key={sIdx} className="flex items-start gap-2">
      {!startsWithCustomIcon && (
        <CheckCircle2 className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
      )}
      <div className="text-xs sm:text-sm text-slate-700 leading-relaxed text-justify w-full">
        {sc.includes('\n') || startsWithCustomIcon || isHtml ? (
          <FormattedText text={sc} />
        ) : (
          renderFormattedInline(sc)
        )}
      </div>
    </li>
  );
};

export const RulesSection: React.FC<RulesSectionProps> = ({ rules, supplementaryRegulations }) => {
  const letRule = supplementaryRegulations?.find(r => r.id === 'let_rule') || DEFAULT_SUPPLEMENTARY_REGULATIONS[0];
  const walkoverRule = supplementaryRegulations?.find(r => r.id === 'walkover_rule') || DEFAULT_SUPPLEMENTARY_REGULATIONS[1];

  return (
    <section className="py-8 bg-slate-50/70 border-b border-slate-200">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 space-y-6 sm:space-y-8">
        {/* Section Header */}
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center font-bold shadow-xs shrink-0">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 font-display tracking-tight">
              Điều Lệ &amp; Thể Thức Thi Đấu
            </h2>
            <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
              Quy định chi tiết về thể thức tính điểm, luật đánh lại và xử lý bỏ cuộc
            </p>
          </div>
        </div>

        {/* Detailed Rules Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 sm:gap-5">
          {rules.map((rule, idx) => (
            <div
              key={idx}
              className="bg-white p-5 sm:p-6 rounded-2xl border border-slate-200 shadow-xs flex flex-col justify-start hover:border-slate-300 transition-colors"
            >
              <div className="space-y-3.5">
                <div className="flex items-center gap-2.5 pb-3 border-b border-slate-100">
                  <span className="w-7 h-7 rounded-lg bg-blue-100 text-blue-700 font-bold text-xs sm:text-sm flex items-center justify-center shadow-2xs shrink-0">
                    0{idx + 1}
                  </span>
                  <h3 className="text-base font-bold text-slate-900 leading-snug">{rule.stage}</h3>
                </div>

                <div className="text-xs sm:text-sm text-slate-700 leading-relaxed font-normal text-justify space-y-2">
                  <FormattedText text={rule.formatDescription} />
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Supplementary Regulations: Quả Cầu Đánh Lại & Xử Lý Bỏ Cuộc / Bỏ Giải */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-5">
          {/* Card 1: Các Trường Hợp Đánh Lại Điểm (Pha Cầu Hỏng / Let) */}
          <div className="bg-white p-5 sm:p-6 rounded-2xl border border-blue-200/90 shadow-xs space-y-4 relative overflow-hidden">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0 border border-blue-200 shadow-2xs">
                <span className="text-base font-black">🔄</span>
              </div>
              <div>
                <h3 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
                  {letRule.title}
                </h3>
                {letRule.subtitle && (
                  <p className="text-xs sm:text-sm text-slate-500">
                    {letRule.subtitle}
                  </p>
                )}
              </div>
            </div>

            <div className="space-y-2.5 text-xs sm:text-sm text-slate-700">
              {letRule.items.map((item, idx) => (
                <div key={item.id || idx} className="p-3 rounded-xl bg-slate-50 border border-slate-100 flex items-start gap-2.5">
                  <span className="w-5 h-5 rounded-md bg-blue-100 text-blue-700 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                    {item.label || idx + 1}
                  </span>
                  <div className="text-justify w-full">
                    {item.title && (
                      <strong className="text-slate-900 block text-xs sm:text-sm mb-0.5 text-left">
                        {item.title}
                      </strong>
                    )}
                    <span className="leading-relaxed">
                      <FormattedText text={item.description} />
                    </span>
                  </div>
                </div>
              ))}
            </div>

            {(letRule.noteContent || letRule.noteTitle) && (
              <div className="p-3.5 sm:p-4 rounded-xl bg-blue-50/90 border border-blue-200 text-xs sm:text-sm text-slate-800 leading-relaxed">
                <div className="leading-relaxed text-slate-700 font-normal">
                  {letRule.noteTitle && (
                    <strong className="font-bold text-blue-950 mr-1.5 inline">
                      {letRule.noteTitle}
                    </strong>
                  )}
                  <span className="inline">
                    {letRule.noteContent}
                  </span>
                </div>
              </div>
            )}
          </div>

          {/* Card 2: Quy Định Xử Lý Bỏ Cuộc / Bỏ Giải (Walkover & Forfeiture) */}
          <div className="bg-white p-5 sm:p-6 rounded-2xl border border-amber-200/90 shadow-xs space-y-4 relative overflow-hidden">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-amber-50 text-amber-700 flex items-center justify-center shrink-0 border border-amber-200 shadow-2xs">
                <span className="text-base font-black">⚠️</span>
              </div>
              <div>
                <h3 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
                  {walkoverRule.title}
                </h3>
                {walkoverRule.subtitle && (
                  <p className="text-xs sm:text-sm text-slate-500">
                    {walkoverRule.subtitle}
                  </p>
                )}
              </div>
            </div>

            <div className="space-y-2.5 text-xs sm:text-sm text-slate-700">
              {walkoverRule.items.map((item, idx) => (
                <div key={item.id || idx} className="p-3 rounded-xl bg-slate-50 border border-slate-100 flex items-start gap-2.5">
                  <span className="w-5 h-5 rounded-md bg-amber-100 text-amber-800 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                    {item.label || String.fromCharCode(65 + idx)}
                  </span>
                  <div className="text-justify w-full">
                    {item.title && (
                      <strong className="text-slate-900 block text-xs sm:text-sm mb-0.5 text-left">
                        {item.title}
                      </strong>
                    )}
                    <span className="leading-relaxed">
                      <FormattedText text={item.description} />
                    </span>
                  </div>
                </div>
              ))}
            </div>

            {(walkoverRule.noteContent || walkoverRule.noteTitle) && (
              <div className="p-3.5 sm:p-4 rounded-xl bg-amber-50/90 border border-amber-200 text-xs sm:text-sm text-slate-800 leading-relaxed">
                <div className="leading-relaxed text-slate-700 font-normal">
                  {walkoverRule.noteTitle && (
                    <strong className="font-bold text-amber-950 mr-1.5 inline">
                      {walkoverRule.noteTitle}
                    </strong>
                  )}
                  <span className="inline">
                    {walkoverRule.noteContent}
                  </span>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

